### ISSUE TITLE
Library evaluation for our experiment

### ISSUE THREAD

**Issue by LastStarDust** [HEP-SF/TrickTrack#19]
Hello!
My name is Giorgio Pintaudi and I am a Ph.D. student based in Japan, working on the T2K experiment (the near detector side).

I am here because I am evaluating your library to see if it can fit our experiment requirements/configuration. Sorry for the long message, but before asking questions I would like to describe our background a little.

We have been using for many years the cellular automaton algorithm to find tracks. However, as is usually the case in HEP, our C++ codebase is of dubious quality, to say the least. I mean no version control, no documentation, no unit tests, no OO design, etc... This year, we added some new subdetectors so we have to update the track finding software anyway, and I am faced with three options.

1. Use the old framework (not really an option because it is a spaghetti code mess)
2. Develop my own library (I have experience in professional software development, so I know how to write good maintainable code, however, I would like to avoid reinventing the wheel)
3. Use a good external library like yours (I am leaning towards this option)

So my questions are:

-  Is this software still actively maintained?
-  Other than the doxygen documentation (very good), is there any other source of documentation? Like websites, articles, reviews, anything. I found this link (cern.ch/tricktrack) but I could not get access to it because I am not CERN based. Does that website contain any useful documentation?
-  I noticed that you provide some Python bindings (very good). As any developer in his right mind, I would always prefer Python over C++ if there is not a specific reason to do otherwise. So, is all the C++ functionality accessible through the Python bindings, or the support is only partial? Do you support or plan to support Python 3?
-  If and only if I happen to make any sizable contribution to the project, can I make a pull request? Will my contribution get any credit? On the other hand, I promise to quote the software in any publication that I might author.

Thank you
Giorgio

**Comment by vvolkl** [comment]
Hi Giorgio!
I'm going to jump straight to your quesion:
* This library is a standalone version of CMS pixel reco code. I currently have other priorities, but will still do bugfixes and support, and probably a port of some upcoming developments in the upstream CMS code.
* The website should work for you too, but it was only showing the doxygen page. For more in-depth information I suggest to look at the relevant chapters in http://cds.cern.ch/record/2293435?ln=en
* No, the python bindings are not very complete, but I also think they only make sense for the "high-level" methods. I think Python 3 should either work or be easy to make work.
* Absolutely!

FInally, I think this library will be a good choice if you are looking to use heterogeneous computing, especially GPUs in the medium-term future, and you may also want to look at  https://github.com/iLCSoft/ConformalTracking or https://github.com/acts-project/acts.
Let me know if you have more question!

**Comment by LastStarDust** [comment]
Thank you for your quick and detailed answer! Please allow me another couple of questions ...

You mentioned two other projects: ConformalTracking and ACTS. I took a very quick look at them and it seems that ConformalTracking implements the cellular automaton algorithm in some way but ACTS doesn't. Can you confirm that?
Are they orthogonal/complementary to TrickTrack or they just offer similar functionality? In other words, what are the differences among them?

Probably you don't need to know but this is the type of detectors I would like to apply the cellular automaton algorithm to ...
The active part of our detectors is all made of scintillators planes read by photodiodes, intertwined with planes of passive material. To make a parallel with collider Physics, neutrino detectors are structurally somewhat between fine graned calorimeters and muon spectrometers. In particular, our detector aims at 4pi angular acceptance

**Comment by hegner** [comment]
Hi Giorgio,

would you be available for a (video) chat towards the end of the week? We'd be happy to help and I think that may make it much easier to discuss all your questions. Which time zone are you in at the moment?

  Benedikt

**Comment by LastStarDust** [comment]
Of course, how nice of you. I live in Japan but this week I am taking the night shift for our experiment, so my internal clock is messed up. The best moment for me would be in the evening (13:00-16:00 CEST or 7:00-10:00 EDT or 16:00-19:00 IST).

**Comment by vvolkl** [comment]
Hi Giorgio, then I propose we have a video chat this Friday, 24.07, at 13:00 CEST.

**Comment by LastStarDust** [comment]
Sounds good to me. Any web conferencing software is ok.

**Comment by LastStarDust** [comment]
I close this because we chose to use a different algorithm in the end.
